name: PlayerLeaderBoards
version: '1.4'
main: com.Mateitaa1.PlayerLeaderBoards.PlayerLeaderBoards
api-version: '1.21'
author: Mateitaa1

commands:
  spawnkillshologram:
    description: Crea un hologram con el top de kills en tu posicion.
    permission: playerleaderboards.admin
  spawndeathshologram:
    description: Crea un hologram con el top de muertes en tu posicion.
    permission: playerleaderboards.admin
  spawnplaytimehologram:
    description: Crea un hologram con el top de tiempo jugado en tu posicion.
    permission: playerleaderboards.admin
  spawnmessageshologram:
    description: Crea un hologram con el top de mensajes en tu posicion.
    permission: playerleaderboards.admin
  spawnblocksminedhologram:
    description: Crea un hologram con el top de bloques minados en tu posicion.
    permission: playerleaderboards.admin
  spawndistancewalkedhologram:
    description: Crea un hologram con el top de distancia caminada en tu posicion.
    permission: playerleaderboards.admin
  removeholograms:
    description: Elimina el hologram mas cercano a tu posicion (radio de 10 bloques).
    permission: playerleaderboards.admin
  leaderboard:
    description: "Muestra el top de una estadistica por chat. Uso: /leaderboard <kills|deaths|playtime|messages|blocksmined|distancewalked>"

permissions:
  playerleaderboards.admin:
    description: Permite crear y eliminar hologramas de PlayerLeaderBoards.
    default: op
